TYPES = [
    "Fire",
    "Water",
    "Grass",
    "Electric",
    "Steel",
    "Dark",
    "Psychic",
    "Dragon",
    "Ice",
    "Ground",
    "Flying",
    "Ghost",
    "Fairy",
    "Poison",
    "Rock",
    "Bug",
    "Normal",
    "Fighting",
]

TYPE_EMOJIS = {
    "Fire": "🔥 Fire",
    "Water": "💧 Water",
    "Grass": "🌿 Grass",
    "Electric": "⚡ Electric",
    "Steel": "⚙️ Steel",
    "Dark": "🌑 Dark",
    "Psychic": "🔮 Psychic",
    "Dragon": "🐉 Dragon",
    "Ice": "❄️ Ice",
    "Ground": "🏜️ Ground",
    "Flying": "🦅 Flying",
    "Ghost": "👻 Ghost",
    "Fairy": "🧚 Fairy",
    "Poison": "☠️ Poison",
    "Rock": "🪨 Rock",
    "Bug": "🐛 Bug",
    "Normal": "⚪ Normal",
    "Fighting": "🥊 Fighting",
}

RARITY_STYLING = {
    "Common": {
        "title": "🎲 Gacha: New Companion Discovered!",
        "rarity_formatted": "⚪ **Common**",
        "color": 0x979C9F,  # Grey
    },
    "Rare": {
        "title": "✨ Gacha: Epic Companion Discovered! ✨",
        "rarity_formatted": "💎 ✨ **Epic** ✨ 💎",
        "color": 0x9B59B6,  # Purple
    },
    "Epic": {
        "title": "✨ Gacha: Epic Companion Discovered! ✨",
        "rarity_formatted": "💎 ✨ **Epic** ✨ 💎",
        "color": 0x9B59B6,  # Purple
    },
    "Sub-Legendary": {
        "title": "⚡ Gacha: LEGENDARY Companion Discovered! ⚡",
        "rarity_formatted": "✨ ⚡ **Legendary** ⚡ ✨",
        "color": 0xE67E22,  # Orange
    },
    "Legendary": {
        "title": "⚡ Gacha: LEGENDARY Companion Discovered! ⚡",
        "rarity_formatted": "✨ ⚡ **Legendary** ⚡ ✨",
        "color": 0xE67E22,  # Orange
    },
    "God": {
        "title": "👑 Gacha: GOD Companion Discovered! 👑",
        "rarity_formatted": "🌌 🔥 🌟 **GOD** 🌟 🔥 🌌",
        "color": 0xF1C40F,  # Gold/Yellow
    },
}

CONCEPTS = {
    "Object": [
        "Clock",
        "Compass",
        "Key",
        "Lantern",
        "Mirror",
        "Bell",
        "Book",
        "Shield",
        "Sword",
        "Hourglass",
        "Telescope",
        "Crown",
    ],
    "Weather": [
        "Rain",
        "Cloud",
        "Wind",
        "Lightning",
        "Snow",
        "Fog",
        "Rainbow",
        "Storm",
        "Sun",
        "Eclipse",
        "Meteor",
        "Aurora",
    ],
    "Mythology": [
        "Griffin",
        "Pegasus",
        "Phoenix",
        "Chimera",
        "Kirin",
        "Cerberus",
        "Hydra",
        "Sphinx",
        "Unicorn",
        "Yeti",
        "Thunderbird",
        "Basilisk",
    ],
    "Food": [
        "Cake",
        "Juice",
        "Tea",
        "Cookie",
        "Candy",
        "Sushi",
        "Burger",
        "Pizza",
        "IceCream",
        "Donut",
        "Coffee",
        "Honey",
    ],
    "Profession": [
        "Doctor",
        "Engineer",
        "Artist",
        "Chef",
        "Detective",
        "Astronaut",
        "Scientist",
        "Pilot",
        "Firefighter",
        "Writer",
        "Musician",
        "Teacher",
    ],
    "Abstract": [
        "Gravity",
        "Time",
        "Space",
        "Sound",
        "Shadow",
        "Light",
        "Dream",
        "Memory",
        "Chaos",
        "Order",
        "Entropy",
        "Harmony",
    ],
    "Scientific": [
        "Atom",
        "Crystal",
        "Magnet",
        "Prism",
        "Helix",
        "Nebula",
        "Laser",
        "Fossil",
        "Virus",
        "Galaxy",
        "Quantum",
        "Volcano",
    ],
    "Geographical": [
        "Desert",
        "Jungle",
        "Ocean",
        "Mountain",
        "Swamp",
        "Canyon",
        "Tundra",
        "Oasis",
        "Glacier",
        "Island",
        "Cave",
        "Forest",
    ],
    "Historical": [
        "Knight",
        "Pharaoh",
        "Samurai",
        "Viking",
        "Pirate",
        "Ninja",
        "Gladiator",
        "Wizard",
        "Alchemist",
        "Philosopher",
        "Explorer",
        "Inventor",
    ],
    "Chemical": [
        "Acid",
        "Rust",
        "Mercury",
        "Sulfur",
        "Plasma",
        "Toxic",
        "Alloy",
        "Carbon",
        "Copper",
        "Neon",
        "Quartz",
        "Ether",
    ],
    "Botanical": [
        "Spore",
        "Bramble",
        "Lotus",
        "Ivy",
        "Moss",
        "Cactus",
        "Fern",
        "Willow",
        "Orchid",
        "Maple",
        "Thorn",
        "Nectar",
    ],
    "Marine": [
        "Coral",
        "Anemone",
        "Abyss",
        "Tide",
        "Whirlpool",
        "Reef",
        "Shell",
        "Pearl",
        "Kraken",
        "Kelpie",
        "Siren",
        "Leviathan",
    ],
    "Astral": [
        "Comet",
        "Pulsar",
        "Supernova",
        "Constellation",
        "Quasar",
        "Orbit",
        "Zenith",
        "Nadir",
        "Solaris",
        "Lunaria",
        "Void",
        "Etheria",
    ],
    "Thermodynamic": [
        "Spark",
        "Embers",
        "Steam",
        "Frost",
        "Ash",
        "Magma",
        "Fume",
        "Blaze",
        "Chill",
        "Vapor",
        "Pyre",
        "Geyser",
    ],
    "Geological": [
        "Obsidian",
        "Amber",
        "Clay",
        "Silt",
        "Geode",
        "Basalt",
        "Marble",
        "Flint",
        "Granite",
        "Sulfur",
        "Talc",
        "Bedrock",
    ],
    "Mechanical": [
        "Gear",
        "Piston",
        "Spring",
        "Valve",
        "Sprocket",
        "Lever",
        "Pulley",
        "Rotor",
        "Crank",
        "Turbine",
        "Dynamo",
        "Engine",
    ],
    "Acoustic": [
        "Echo",
        "Pitch",
        "Tempo",
        "Chime",
        "Hum",
        "Rhythm",
        "Melody",
        "Sonata",
        "Reverb",
        "Frequency",
        "Decibel",
        "Vibration",
    ],
    "Meteorological": [
        "Drizzle",
        "Gale",
        "Blizzard",
        "Typhoon",
        "Cyclone",
        "Breeze",
        "Squall",
        "Monsoon",
        "Zephyr",
        "Draft",
        "Gust",
        "Hail",
    ],
    "Physical": [
        "Friction",
        "Inertia",
        "Velocity",
        "Tension",
        "Torque",
        "Momentum",
        "Impact",
        "Kinetic",
        "Static",
        "Thermal",
        "Elastic",
        "Magnetic",
    ],
    "Eological": [
        "Decay",
        "Growth",
        "Erosion",
        "Sedimentation",
        "Evaporation",
        "Condensation",
        "Freezing",
        "Melting",
        "Combustion",
    ],
}

SYSTEM_PROMPT_TEMPLATE = (
    "You are a world-class pocket monster designer with a deep sense of creativity and narrative. "
    "Your task is to design a fully original fictional monster species inspired by the provided concept, types, and rarity.\n\n"
    "## Design Philosophy\n"
    "- The creature must feel fresh and original — avoid directly copying existing Pokémon designs.\n"
    "- The concept (e.g. 'Clock', 'Rain', 'Griffin') should be deeply reflected in the creature's biology, silhouette, and aesthetic.\n"
    "- Rarity directly determines complexity, visual style, and progression:\n"
    "  • Common → simple, cute, minimalist design with 1–2 defining features.\n"
    "  • Epic → more elaborate, dual-theme integration, elegant or fierce presence.\n"
    "  • Legendary & God → jaw-dropping, mythical, godly power, supreme visual presence, radiates pure energy or cosmic majesty. These must look incredibly cool, powerful, and god-like!\n"
    "- Elemental types must influence the color palette and visual motifs.\n\n"
    "## Evolution Rules\n"
    "{evolution_rules}\n\n"
    "## Visual Prompt Rules (CRITICAL)\n"
    "- In 'visual_prompt', describe ONLY the creature itself — body shape, limb count, proportions, textures, colors, eyes, markings, and any elemental effects on its body.\n"
    "- DO NOT mention any background, environment, ground, sky, weather, shadow, or surrounding objects.\n"
    "- Be highly specific: avoid vague words like 'glowing' or 'colorful'. Specify which part glows, what color, how intensely.\n"
    "- Describe from head to body to limbs/tail in logical order.\n"
    "- Length: {length_rule}"
)
