name: Deploy Kim Application

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: ENV_FILE
          script: |
            cd /root/app/kim

            git pull origin main

            # Ghi đè file .env trên host từ GitHub secret ENV_FILE
            echo "$ENV_FILE" > .env

            docker stop secretary-kim || true
            docker rm secretary-kim || true

            docker build -t secretary-kim-bot .

            docker run -d \
            --name secretary-kim \
            --env-file .env \
            --restart unless-stopped \
            secretary-kim-bot
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
